// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/proto.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Students struct {
	Students             []string `protobuf:"bytes,1,rep,name=students,proto3" json:"students,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Students) Reset()         { *m = Students{} }
func (m *Students) String() string { return proto.CompactTextString(m) }
func (*Students) ProtoMessage()    {}
func (*Students) Descriptor() ([]byte, []int) {
	return fileDescriptor_f55a0e35c85a26d8, []int{0}
}

func (m *Students) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Students.Unmarshal(m, b)
}
func (m *Students) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Students.Marshal(b, m, deterministic)
}
func (m *Students) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Students.Merge(m, src)
}
func (m *Students) XXX_Size() int {
	return xxx_messageInfo_Students.Size(m)
}
func (m *Students) XXX_DiscardUnknown() {
	xxx_messageInfo_Students.DiscardUnknown(m)
}

var xxx_messageInfo_Students proto.InternalMessageInfo

func (m *Students) GetStudents() []string {
	if m != nil {
		return m.Students
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f55a0e35c85a26d8, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Students)(nil), "Students")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() {
	proto.RegisterFile("grpc/proto.proto", fileDescriptor_f55a0e35c85a26d8)
}

var fileDescriptor_f55a0e35c85a26d8 = []byte{
	// 131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2f, 0x2a, 0x48,
	0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x4a, 0x6a, 0x5c, 0x1c, 0xc1, 0x25, 0xa5,
	0x29, 0xa9, 0x79, 0x25, 0xc5, 0x42, 0x52, 0x5c, 0x1c, 0xc5, 0x50, 0xb6, 0x04, 0xa3, 0x02, 0xb3,
	0x06, 0x67, 0x10, 0x9c, 0xaf, 0xc4, 0xce, 0xc5, 0xea, 0x9a, 0x5b, 0x50, 0x52, 0x69, 0x64, 0xc8,
	0xc5, 0xed, 0x19, 0x12, 0xea, 0x92, 0x58, 0x92, 0x98, 0x94, 0x58, 0x9c, 0x2a, 0xa4, 0xc4, 0xc5,
	0xed, 0x9e, 0x5a, 0x02, 0x37, 0x82, 0x4d, 0x0f, 0xac, 0x4a, 0x8a, 0x53, 0x0f, 0x26, 0xa4, 0xc4,
	0xe0, 0x24, 0x16, 0x25, 0xe2, 0x19, 0x12, 0x1a, 0x9c, 0x5a, 0x54, 0x96, 0x5a, 0xa4, 0x8f, 0x70,
	0x41, 0x12, 0x1b, 0x98, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x0a, 0x46, 0x56, 0x96,
	0x00, 0x00, 0x00,
}
