// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RicartArgawala_RequestCriticalSection_FullMethodName = "/RicartArgawala/RequestCriticalSection"
	RicartArgawala_RespondToCSRequest_FullMethodName     = "/RicartArgawala/RespondToCSRequest"
)

// RicartArgawalaClient is the client API for RicartArgawala service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartArgawalaClient interface {
	RequestCriticalSection(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error)
	RespondToCSRequest(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Empty, error)
}

type ricartArgawalaClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartArgawalaClient(cc grpc.ClientConnInterface) RicartArgawalaClient {
	return &ricartArgawalaClient{cc}
}

func (c *ricartArgawalaClient) RequestCriticalSection(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RicartArgawala_RequestCriticalSection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartArgawalaClient) RespondToCSRequest(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, RicartArgawala_RespondToCSRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartArgawalaServer is the server API for RicartArgawala service.
// All implementations must embed UnimplementedRicartArgawalaServer
// for forward compatibility.
type RicartArgawalaServer interface {
	RequestCriticalSection(context.Context, *Request) (*Empty, error)
	RespondToCSRequest(context.Context, *Response) (*Empty, error)
	mustEmbedUnimplementedRicartArgawalaServer()
}

// UnimplementedRicartArgawalaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartArgawalaServer struct{}

func (UnimplementedRicartArgawalaServer) RequestCriticalSection(context.Context, *Request) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCriticalSection not implemented")
}
func (UnimplementedRicartArgawalaServer) RespondToCSRequest(context.Context, *Response) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RespondToCSRequest not implemented")
}
func (UnimplementedRicartArgawalaServer) mustEmbedUnimplementedRicartArgawalaServer() {}
func (UnimplementedRicartArgawalaServer) testEmbeddedByValue()                        {}

// UnsafeRicartArgawalaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartArgawalaServer will
// result in compilation errors.
type UnsafeRicartArgawalaServer interface {
	mustEmbedUnimplementedRicartArgawalaServer()
}

func RegisterRicartArgawalaServer(s grpc.ServiceRegistrar, srv RicartArgawalaServer) {
	// If the following call pancis, it indicates UnimplementedRicartArgawalaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RicartArgawala_ServiceDesc, srv)
}

func _RicartArgawala_RequestCriticalSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartArgawalaServer).RequestCriticalSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartArgawala_RequestCriticalSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartArgawalaServer).RequestCriticalSection(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RicartArgawala_RespondToCSRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartArgawalaServer).RespondToCSRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RicartArgawala_RespondToCSRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartArgawalaServer).RespondToCSRequest(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

// RicartArgawala_ServiceDesc is the grpc.ServiceDesc for RicartArgawala service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RicartArgawala_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RicartArgawala",
	HandlerType: (*RicartArgawalaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCriticalSection",
			Handler:    _RicartArgawala_RequestCriticalSection_Handler,
		},
		{
			MethodName: "RespondToCSRequest",
			Handler:    _RicartArgawala_RespondToCSRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto.proto",
}
